services:
  dotnet:
    image: devcontainer:dotnet
    build:
      context: .
    entrypoint: tail -F /dev/null
    ports:
      - 5000:5000
      - 5001:5001
    user: developer
    volumes:
      - ../:/work
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123
