services:
  dotnet:
    image: devcontainer:dotnet
    build:
      context: .
    entrypoint: tail -F /dev/null
    ports:
      - 5000:5000
      - 5001:5001
    user: developer
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_PORT
      - POSTGRES_HOST
      - JWT_SECRET
      - JWT_ISSUER
      - JWT_AUDIENCE
    volumes:
      - ../:/work
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.3-bookworm
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  database:
    driver: local

